### ISSUE TITLE
DeepgramApiError: Please try again later. (Status: 503)

### ISSUE THREAD

**Issue by roperi** [deepgram/python-sdk#300]
## What is the current behavior?

Getting a 503 error  when `response = deepgram.listen.prerecorded.v("1").transcribe_url(AUDIO_URL, options, timeout=300)`.

```
Version.v ENTER
Version.v ENTER
version: 1
version: 1
path: deepgram.clients.prerecorded.v1.client
path: deepgram.clients.prerecorded.v1.client
className: PreRecordedClient
className: PreRecordedClient
Version.v succeeded
Version.v succeeded
Version.v LEAVE
Version.v LEAVE
PreRecordedClient.transcribe_url ENTER
url: https://api.deepgram.com/v1/listen
source: {'url': 'https://website.com/media.mp3'}
PrerecordedOptions switching class -> json
options: {'alternatives': None, 'callback': None, 'callback_method': None, 'custom_intent': None, 'custom_intent_mode': None, 'custom_topics': None, 'custom_topic_mode': None, 'detect_entities': None, 'detect_language': None, 'detect_topics': None, 'diarize': True, 'diarize_version': None, 'dictation': None, 'extra': None, 'filler_words': None, 'intents': None, 'keywords': None, 'language': None, 'measurements': None, 'model': 'nova-2', 'multichannel': None, 'numerals': None, 'paragraphs': None, 'profanity_filter': None, 'punctuate': None, 'redact': None, 'replace': None, 'search': None, 'sentiment': None, 'smart_format': True, 'summarize': 'v2', 'tag': None, 'tier': None, 'topics': True, 'utt_split': None, 'utterances': None, 'version': None}
addons: None
Exception: DeepgramApiError: Please try again later. (Status: 503)
```

## Expected behavior

I should get a response without any 503.  

## Please tell us about your environment

Debian 10
Python 3.10.12

**Comment by dvonthenen** [comment]
Hi @roperi 

The `timeout=300` isnt valid. You need to declare a timeout using an `httpx` object:
https://github.com/deepgram/deepgram-python-sdk/blob/main/deepgram/clients/abstract_sync_client.py#L99

**Comment by dvonthenen** [comment]
The example here words for me:
https://github.com/deepgram/deepgram-python-sdk/blob/main/examples/prerecorded/url/main.py

Does it work for you?

**Comment by dvonthenen** [comment]
There seems like there might have been a hiccup in the service this morning. I can take a look but I would need more information like the `request_id`.

**Comment by dvonthenen** [comment]
> Also, how can I get the `request_id` if I'm getting the 503, @dvonthenen ?

Good point But I'm running the examples right now and not running into any problems

**Comment by dvonthenen** [comment]
I'm going to try to reconstruct your query using the log output you have right here

**Comment by dvonthenen** [comment]
it's possible the MP3 is" invalid ". Can you download the MP3 file on your local system and then use ffprobe and then copy the output of that command here.

**Comment by dvonthenen** [comment]
Interesting. We'll take a look at it in a bit.

I assume then now other files besides this one work fine? And maybe the qualified even more other files that haven't been generated using the same method as this file?

**Comment by dvonthenen** [comment]
No worries. Yea, I didn't do anything I my end. If it happens again, drop me a line.

**Comment by kpetrovsky-audibene** [comment]
@roperi curious how it worked for you since? We are trying to use Deepgram for our calls (more details at https://github.com/orgs/deepgram/discussions/906), and it fails quite often. The fail pattern clearly indicates some server issues - it can work fine for a few days, and then suddenly chunks of requests start to fail - after a delay of 40+ seconds, exactly as you have described.

**Comment by dvonthenen** [comment]
Hi @roperi 

A 503 is usually a server error on our end. I would recommend adding functionality to perform retries with some type of backoff mechanism.

**Comment by kpetrovsky-audibene** [comment]
@dvonthenen the problem we are experiencing is that 503s usually go in chunks - for 30-120 minutes >50% of requests would be erroring out. Is that expected and normal, or some parameters in the request can trigger that especially strongly? I've provided more details at https://github.com/orgs/deepgram/discussions/906.
And it's also important to understand if the same behavior is replicated with the realtime transcription, or those servers are independent and have better scaling?

**Comment by dvonthenen** [comment]
Is this for pre-recorded or live streaming audio? I assume based on the original post, it's for pre-recorded. If so, the other thing you should check is:
1. The error message, and 
2. You have increased the timeout to a sufficiently value based on the size/length of audio

There is so much going on in this thread with multiple different issues from multiple people. If you want to chat in Discord, that might clear some of the confusion.

**Comment by kpetrovsky-audibene** [comment]
@dvonthenen sure, will message you on Discord in a second :)
